### ISSUE TITLE
Disable sticky sidebars?

### ISSUE THREAD

**Issue by WillemSleegers** [rethinkpriorities/bookdown-template#1]
By default, the sidebars are sticky, which means they will continue to be visible as you scroll down (i.e., they stick to the top of the window).

We could disable this so that they are static and stay at the top of the page, and thus don't scroll along when you scroll. 

The upside of this is that it reduces screen clutter for the longer posts.

**Comment by WillemSleegers** [comment]
A downside is that you then need to scroll all the way back up to toggle the code or navigate away.

**Comment by WillemSleegers** [comment]
This is also relevant for #6

**Comment by daaronr** [comment]
Maybe make only the left sidebar 'sticky'?  Tbh I'd like to get rid of the right sidebar altogether, and have that space back, as you know

**Comment by WillemSleegers** [comment]
It's relatively easy to get rid of it, but the trick is to then still have a TOC on the left that can go deeper than just 1 depth.

**Comment by daaronr** [comment]
Ah, that's easy to do in the gitbook style but not the bs4 I guess.

Let's not beat our heads against the wall on this one -- I suspect that the bs4 people will make an update allowing this? Or maybe we can file a request for it?

**Comment by WillemSleegers** [comment]
This issue is addressed by us switching back to the gitbook format.
