### ISSUE TITLE
Hovering footnotes disappear on left margin 

### ISSUE THREAD

**Issue by daaronr** [rethinkpriorities/bookdown-template#11]
<img width="849" alt="image" src="https://user-images.githubusercontent.com/8229168/151270146-86e04ab8-1641-42da-96ee-69399f7fb77c.png">

**Comment by WillemSleegers** [comment]
This one is trickier. I have a solution but it breaks other things. 

Does this also happen with small footnotes?

**Comment by daaronr** [comment]
Yes, if I understand your question, it does:

<img width="900" alt="image" src="https://user-images.githubusercontent.com/8229168/151440473-cfe47616-333c-436c-b732-776fde07c8fb.png">


Note the behavior of footnotes when I build is a bit erratic... sometimes it makes them actual footnotes (at bottom), sometimes it hovers, and sometimes it clicks

There's a bunch of white space on the left. Can't we 'reclaim it'?

![Uploading image.png…]()

**Comment by WillemSleegers** [comment]
It's possible to take advantage of that white space but then when you get close to the TOC on the left, you get the same issue. =(

**Comment by daaronr** [comment]
Can we do a 'workaround' for this that at least keeps them from being illegible, for now?

(By the way, regardless of this, why do we need all that whitespace on the left? is it a devices thing?)

**Comment by WillemSleegers** [comment]
The white space is the TOC section of the page, as well as the arrow that takes you to the previous section in the book. We could remove the arrow to create more room, but this is unacceptable anyway because people have different screen sizes so some of them will still have the problem while others will not.

The best solution is probably to use non-hoverable footnotes. With foldable sections and callout blocks we already have (too) many different ways to say something.

I will probably start some work on creating our own custom format so that we have full control over the page; that will be able to resolve the issue.

**Comment by daaronr** [comment]
> The best solution is probably to use non-hoverable footnotes

That seems like a big loss to me. What about something like 'putting footnotes on their own line... or always flushing to the right' as a workaround?

**Comment by WillemSleegers** [comment]
What about using footnotes that show up in the bottom when you hover/click? See http://www.bigfootjs.com for a demo.

**Comment by daaronr** [comment]
That would be fine... as long as you see them when you hover or click them. 

But I don't see it in that demo (at least not anywhere immediately obvious)

**Comment by daaronr** [comment]
In the version you pushed, I still see the footnote overlap problem, a least while the outline is showing: 

![image](https://user-images.githubusercontent.com/8229168/152248772-2b3a7d79-dc4a-4fa6-a0a5-e09abf0c4b51.png)

<br>

When I pull your changes and build it on my machine I am back to the 'end of document' footnote behavior:

![image](https://user-images.githubusercontent.com/8229168/152248963-e7ecf516-5736-42b9-934a-f579c5ca01d6.png)

**Comment by WillemSleegers** [comment]
I fixed this issue in the new template.
