### ISSUE TITLE
(minor) inline r code, itemized lists,  and latex content doesn't work in foldables

### ISSUE THREAD

**Issue by daaronr** [rethinkpriorities/bookdown-template#14]
See template f`foldable-sections.html#what-kind-of-content-can-foldables-containt`

- inline r code greys out the foldable (fairly important)
- latex greys out the foldable (not very important)
- itemized list begin with the list outside the foldable (a bit important)

**Comment by WillemSleegers** [comment]
Should be fixed as well. Do note you have to be careful with the button html code; I recommend copy-pasting it from a version that works and mind using the right quotations/spaces/newlines, etc.

**Comment by daaronr** [comment]
Wow, awesome!
