### ISSUE TITLE
offset quotes

### ISSUE THREAD

**Issue by daaronr** [rethinkpriorities/bookdown-template#22]
I can't get the normal 

> I am a quote ... to work 

using the `>` symbol

I did find a partial workaround though. See: https://rethinkpriorities.github.io/bookdown-template/citations.html#offset-quotes

**Comment by WillemSleegers** [comment]
I added a styling for block quotes and updated the template with a chapter to showcase them.

**Comment by daaronr** [comment]
Looking good. I updated the explanation and demonstration in commit 65fd13a
