### ISSUE TITLE
Folding boxes sometimes come out as  an unopenable grey strip ... depending on location?

### ISSUE THREAD

**Issue by daaronr** [rethinkpriorities/bookdown-template#5]
Folding boxes are only an unopenable grey strip if there's not much text within:

```{block2,  type='fold'}

Yes: I just did.

```

Becomes [see link](https://daaronr.github.io/dr-rstuff/bs4_bookdown_template/docs/about.html#questions-with-folded-answers-folded-expanded-discussions)

![image](https://user-images.githubusercontent.com/8229168/148131931-e9827247-9042-4643-8ff5-c707c607320d.png)

It's unopenable too.

**Comment by daaronr** [comment]
I made a close to mwe of the problem in the branch of EAS [HERE](https://github.com/rethinkpriorities/ea-data/tree/mwe_eas_bs4)

It's not about the amount of content in the foldable, it seems.

**Comment by WillemSleegers** [comment]
Sweet; that's helpful! I just replicated it by simply putting 2 of them in the same chapter, and I get the same issue.

**Comment by WillemSleegers** [comment]
Issue should be fixed with the latest push.

**Comment by WillemSleegers** [comment]
Note that I changed this feature a bit with the new template. My issue was with the performance of our solution (the folded text being briefly visible before being hidden, for example), so I changed the way it works. Some new testing is required!

**Comment by daaronr** [comment]
I tested it with multiple foldables and it seems good for now. I actually like that you can put different 'show me more' texts in. That will be helpful.

**Comment by daaronr** [comment]
Issue came up again and the problem was that you need the 
```<button class="fold-button">  Show me more  or any text </button>```
to all be on one line
