### ISSUE TITLE
Right sidebar (bookdown::bs_4): takes up too much space can it 'hide'? Can we reduce its profile?

### ISSUE THREAD

**Issue by daaronr** [rethinkpriorities/bookdown-template#6]
The right 'subsections' sidebar takes up a lot of screen real estate and it's sometimes distracting IMO. 

@willemsleegers
Is there a way to
1. Have it hidden unless you mouse over it?
2. Make it less prominent
3. Make it display up to H2 (## level) only?

**Comment by WillemSleegers** [comment]
Regarding option 3; I don't think it is possible. You can use a H4 instead, that won't show up. We could then always alter the font size of a H4 using CSS.

**Comment by daaronr** [comment]
Hmm, replacing H3s with H4's is a really annoying workaround. I'm shocked this isn't possible. Oh well.

**Comment by WillemSleegers** [comment]
It's not elegant but why is it really annoying?

**Comment by daaronr** [comment]
moved to 'deferred' because we seem to be switching back to Gitbook style.

**Comment by daaronr** [comment]
Fwiw: 
> It's not elegant but why is it really annoying?

Making H3's into H4's is annoying because I have an overall system for thinking about these heading levels across docs.

**Comment by WillemSleegers** [comment]
By switching to the gitbook format we also address this issue, so solved I think!

Despite that, I do think a general attitude we should have is that we want to adapt the format to our needs and that we adapt our needs to the format. 

In the words of [Yihui](https://bookdown.org/yihui/bookdown/faq.html): 

> The most challenging thing in the world is not to learn fancy technologies, but control your own wild heart.

**Comment by daaronr** [comment]
true. And maybe I overestimate how much investment I've put in to 'which level of tags are in my markdowns'/

I think the margins are pretty good now, we can tweak a bit, but it's not bad.
