### ISSUE TITLE
transition (back) to 'new version' of gitbook style

### ISSUE THREAD

**Issue by daaronr** [rethinkpriorities/bookdown-template#9]

**Comment by daaronr** [comment]
@WillemSleegers As we are (probably) moving back to gitbook, I created another branch of EA-data called [eas_new_style](https://github.com/rethinkpriorities/ea-data/tree/eas_new_style) 

... I'll be working there and gradually incorporating the 'new gitbook style' you are building. 

I didn't want to just rename the `eas_bs4...` branch because that would get (more) confusing

**Comment by WillemSleegers** [comment]
Okay.

I updated the template. Let me know if something doesn't work as intended. Otherwise, this issue can be closed.

**Comment by daaronr** [comment]
seems OK, but there are some (newly discovered) style issues I'll raise separately.
